run:
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - bodyclose
    - canonicalheader
    - containedctx
    - copyloopvar
    - err113
    - errorlint
    - gofumpt
    - goimports
    - gosec
    - makezero
    - nilerr
    - noctx
    - paralleltest
    - perfsprint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - thelper
    - tparallel
    - usestdlibvars
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true
